In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1


# Tensor creation

### Scalar

In [5]:
scaler = torch.tensor(7) 
print(scaler)
print(scaler.ndim) #scaler has no dimension as it is a single number
print(scaler.item()) #tensor is returned as python int

tensor(7)
0
7


### Vector

In [8]:
vector = torch.tensor([2,3])
print(vector)
print(vector.ndim)#vector has one dimension
print(vector.shape)

tensor([2, 3])
1
torch.Size([2])


### Matrix

In [24]:
MATRIX = torch.tensor([[2,3],
                       [4,9]])
print(MATRIX )
print(MATRIX .ndim) #matrix has two dimension
print(MATRIX .shape)#In this case, the shape is two rows and two columns

tensor([[2, 3],
        [4, 9]])
2
torch.Size([2, 2])


### Tensor

In [25]:
TENSOR = torch.tensor([[[2,3,4], 
                       [3,4,2], 
                       [3,4,5]]])
print(TENSOR)
print(TENSOR.ndim) #tensor has three or more dimension
print(TENSOR.shape)#In this case, the shape is three rows and three columns
print(TENSOR[0][1])
print(TENSOR[0][2][2])

tensor([[[2, 3, 4],
         [3, 4, 2],
         [3, 4, 5]]])
3
torch.Size([1, 3, 3])
tensor([3, 4, 2])
tensor(5)


0 dimensional tensor is called scalar, 1 dimensional tensor is called vector and 2 dimensional tensor is called matrix.

### Random tensors
Random tensors are important because most often neural network start with random numbers and update them according to the data.

In [31]:
RANDOM_TENSOR = torch.rand(2,3,1,1)
print(RANDOM_TENSOR)
print(RANDOM_TENSOR.ndim)

tensor([[[[0.6405]],

         [[0.6699]],

         [[0.1576]]],


        [[[0.2582]],

         [[0.6087]],

         [[0.8345]]]])
4


In [33]:
RANDOM_TENSOR = torch.rand(size = (2,3,1,1))
print(RANDOM_TENSOR)
print(RANDOM_TENSOR.ndim)

tensor([[[[0.7627]],

         [[0.7239]],

         [[0.1630]]],


        [[[0.5641]],

         [[0.6683]],

         [[0.8716]]]])
4


### Zeros and ones

In [35]:
zeros = torch.zeros(size=(3,4))
print(zeros)
t1 = torch.tensor([[1,2,3,4],[1,2,3,4],[1,2,3,4]])
print(t1)
print(zeros*t1)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [37]:
ones = torch.ones(size=(3,4))
print(ones)
print(ones.dtype)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
torch.float32


### Range of tensors

In [41]:
t1 = torch.arange(1,11)
print(t1)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


In [43]:
t2 = torch.arange(start=1, end=11)
print(t2)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


In [47]:
t3 = torch.arange(start=1, end=21, step=2)
print(t3)

tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])


### Tensors-like

In [52]:
t3_zeros = torch.zeros_like(input=t3)
print(t3_zeros)
t2_ones = torch.ones_like(input=t2)
print(t2_ones)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])


### Tensor datatypes

In [67]:
#float 32 tensor
t_float32 = torch.tensor([2.0,6.0,9.1], dtype=None)
print(t_float32.dtype)
t_float16 = torch.tensor([2.0,6.0,9.1], dtype= torch.float16)
print(t_float16.dtype)
t_float16 = torch.tensor([2.0,6.0,9.1], dtype= torch.float16)
print(t_float16.dtype)
t_int64 = torch.tensor([2,6,9])
print(t_int64.dtype)
t_int32 = torch.tensor([2,6,9], dtype=torch.int32)
print(t_int32.dtype)
t_int16 = torch.tensor([2,6,9], dtype=torch.int16)
print(t_int16.dtype)

torch.float32
torch.float16
torch.float16
torch.int64
torch.int32
torch.int16


### Tensor device

In [76]:
if torch.backends.mps.is_available():
    print("MPS is available")
else:
    print("MPS is not available, using CPU")

MPS is available


In [77]:
# Explicitly set a tensor to the CPU
device = torch.device("cpu")
tensor = torch.tensor([1.0, 2.0, 3.0], device=device)
print("Tensor is on:", tensor.device)

Tensor is on: cpu


In [78]:
#Set a tensor on GPU
t_float32 = torch.tensor([2.0,6.0,9.1], dtype=torch.float32, device='mps')
print(t_float32.dtype)

torch.float32


### Tracking gradients on the tensor operation

In [79]:
t_float32 = torch.tensor([2.0,6.0,9.1], dtype=torch.float32, device='mps', requires_grad=False)
print(t_float32.dtype)

torch.float32


### Finding details about a tensor

In [80]:
print(t_float32)
print(f"Datatype of the tesor: {t_float32.dtype}")
print(f"Shape of the tensor: {t_float32.shape}")
print(f"Dimension of the tensor: {t_float32.ndim}")
print(f"Size of the tensor: {t_float32.size}")
print(f"Device tensor is on: {t_float32.device}")

tensor([2.0000, 6.0000, 9.1000], device='mps:0')
Datatype of the tesor: torch.float32
Shape of the tensor: torch.Size([3])
Dimension of the tensor: 1
Size of the tensor: <built-in method size of Tensor object at 0x13b2359f0>
Device tensor is on: mps:0


# Tensor Operations

### Addition

In [81]:
t1 = torch.tensor([2,3,1])
print(t1+5)

tensor([7, 8, 6])


In [82]:
t2 = torch.tensor([3,3,3])
print(t1+t2)

tensor([5, 6, 4])


### Multiplication

In [83]:
print(t1*5)

tensor([10, 15,  5])


In [84]:
print(t1*t2)

tensor([6, 9, 3])


In [89]:
#in-built functions
t1.mul(t2)

tensor([6, 9, 3])

#### Element wise multiplication

In [100]:
print(t1, '*', t1, 'equals', t1*t1)

tensor([2, 3, 1]) * tensor([2, 3, 1]) equals tensor([4, 9, 1])


In [102]:
%%time
total = 0
for i in range(len(t1)):
    total += t1[i]*t1[i]
print(total)

tensor(14)
CPU times: user 952 µs, sys: 3.89 ms, total: 4.85 ms
Wall time: 9.53 ms


#### Matrix multiplication

In [106]:
print(torch.matmul(t1,t1))

tensor(14)


In [108]:
print(t1@t1)

tensor(14)


In [104]:
%%time
total = torch.matmul(t1,t1)
print(total)

tensor(14)
CPU times: user 1.19 ms, sys: 1.69 ms, total: 2.88 ms
Wall time: 2.87 ms


Matrix multiplication is faster than element wise multiplication

To avoid shape errors, the rules to perform matrix multiplication should be followed.
- The inner dimensions must match. The column size of first matrix should be equal to row size of second matrix
- The resulting matrix has shape of outer dimension.

In [119]:
t5 = torch.tensor([[2,3,4],[5,1,2]])
t6 = torch.tensor([[2,3], [1,2], [3,4]])

In [128]:
print(t5.shape)
print(t6.shape)
#We can use torch.matmul or torch.mm or @
print(torch.matmul(t5,t6).shape)
print(torch.mm(t5,t6).shape)
print((t5@t6).shape)

torch.Size([2, 3])
torch.Size([3, 2])
torch.Size([2, 2])
torch.Size([2, 2])
torch.Size([2, 2])


### Substraction

In [85]:
print(t1-5)

tensor([-3, -2, -4])


In [86]:
print(t1-t2)

tensor([-1,  0, -2])


### Division

In [87]:
print(t1/2)

tensor([1.0000, 1.5000, 0.5000])


In [88]:
print(t1/t2)

tensor([0.6667, 1.0000, 0.3333])


In [95]:
(8+1)//2

4

In [96]:
(8+2)//2

5

In [97]:
(9+1)//2

5

In [98]:
(9+2)//2

5

### Reshaping tensors

In [151]:
t6

tensor([[2, 3],
        [1, 2],
        [3, 4]])

In [152]:
t6_reshaped = t6.reshape(2,3)
print(t6_reshaped)
print(t6.shape)
print(t6_reshaped.shape)

tensor([[2, 3, 1],
        [2, 3, 4]])
torch.Size([3, 2])
torch.Size([2, 3])


### View
Return a view of an input tensor of certain shape but keep the same memory as the original tensor

In [153]:
t6_view = t6.view(2,3)
print(t6.shape)
print(t6_view.shape)

torch.Size([3, 2])
torch.Size([2, 3])


In [154]:
t6_view[:,0] = 0
print(t6_view)
print(t6)

tensor([[0, 3, 1],
        [0, 3, 4]])
tensor([[0, 3],
        [1, 0],
        [3, 4]])


Changing t6_view changes t6 because a view of a tensor shares the same memory as the original tensor

### Stacking tensors

In [157]:
print(t6_reshaped)
print(t5)

tensor([[0, 3, 1],
        [0, 3, 4]])
tensor([[2., 3., 4.],
        [5., 1., 2.]])


In [160]:
t56 = torch.vstack([t5,t6_reshaped])
print(t56)

tensor([[2., 3., 4.],
        [5., 1., 2.],
        [0., 3., 1.],
        [0., 3., 4.]])


In [163]:
t56 = torch.hstack([t5,t6_reshaped])
print(t56)

tensor([[2., 3., 4., 0., 3., 1.],
        [5., 1., 2., 0., 3., 4.]])


In [162]:
t56 = torch.stack([t5,t6_reshaped], dim=0)
print(t56)

tensor([[[2., 3., 4.],
         [5., 1., 2.]],

        [[0., 3., 1.],
         [0., 3., 4.]]])


In [164]:
t56 = torch.stack([t5,t6_reshaped], dim=1)
print(t56)

tensor([[[2., 3., 4.],
         [0., 3., 1.]],

        [[5., 1., 2.],
         [0., 3., 4.]]])


In [165]:
t56 = torch.stack([t5,t6_reshaped], dim=2)
print(t56)

tensor([[[2., 0.],
         [3., 3.],
         [4., 1.]],

        [[5., 0.],
         [1., 3.],
         [2., 4.]]])


### Squeezing tensors
Removes all single dimensions from a target tensor

In [174]:
print(t5)

tensor([[2., 3., 4.],
        [5., 1., 2.]])


In [175]:
t5.squeeze()

tensor([[2., 3., 4.],
        [5., 1., 2.]])

Here, the first dimension is 2 and second dimension is 3. When we use squeeze() on this tensor, it checks for any dimensions of size 1, but since there are none, it leaves the tensor unchanged.

In [176]:
t7 = torch.tensor([[[2., 3., 4.]],
                       [[5., 1., 2.]]])
print(t7.shape)

torch.Size([2, 1, 3])


In [178]:
t7_squeezed = t7.squeeze()
print(t7_squeezed)
print(t7_squeezed.shape)

tensor([[2., 3., 4.],
        [5., 1., 2.]])
torch.Size([2, 3])


Here, it removed dimension of size 1

### Unsqueezing tensors
Adds a single dimension to a target tensor at a specific dim

In [186]:
t7
print(t7.shape)

torch.Size([2, 1, 3])


In [187]:
t7_unsqueeze = t7.unsqueeze(dim=0)
print(t7_unsqueeze)
print(t7_unsqueeze.shape)

tensor([[[[2., 3., 4.]],

         [[5., 1., 2.]]]])
torch.Size([1, 2, 1, 3])


In [188]:
t7_unsqueeze = t7.unsqueeze(dim=1)
print(t7_unsqueeze)
print(t7_unsqueeze.shape)

tensor([[[[2., 3., 4.]]],


        [[[5., 1., 2.]]]])
torch.Size([2, 1, 1, 3])


### Permute
Rearranges the dimensions of a target tensor in a specified order

In [190]:
t8 = torch.rand(size=(224,224,3)) #(height, width and color channels of pictures)

In [191]:
t8_permuted = t8.permute(2,0,1)
print(t8.shape)
print(t8_permuted.shape)

torch.Size([224, 224, 3])
torch.Size([3, 224, 224])


In [193]:
print(t7)
print(t7.shape)

tensor([[[2., 3., 4.]],

        [[5., 1., 2.]]])
torch.Size([2, 1, 3])


In [195]:
t7_permuted = t7.permute(2,1,0)
print(t7_permuted.shape)
print(t7_permuted)

torch.Size([3, 1, 2])
tensor([[[2., 5.]],

        [[3., 1.]],

        [[4., 2.]]])


# Tensor Aggregation

In [130]:
print(t5)

tensor([[2, 3, 4],
        [5, 1, 2]])


### Minimum

In [132]:
print(torch.min(t5))
print(t5.min())

tensor(1)
tensor(1)


### Maximum

In [133]:
print(torch.max(t5))
print(t5.max())

tensor(5)
tensor(5)


### Mean

In [134]:
print(torch.mean(t5))

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

torch.mean() function requires a tensor of float32 datatype

In [135]:
print(t5.dtype)

torch.int64


In [137]:
t5 = t5.type(torch.float32)
print(t5.dtype)
print(torch.mean(t5))

torch.float32
tensor(2.8333)


### Sum

In [138]:
print(torch.sum(t5))
print(t5.sum())

tensor(17.)
tensor(17.)


### Positional min and max 
Find the position in tensor that has minimum or maximum value

In [143]:
print(t5)

tensor([[2., 3., 4.],
        [5., 1., 2.]])


In [144]:
t5.argmin()

tensor(4)

In [145]:
t5.argmax()

tensor(3)

# Tensor Indexing

In [212]:
t7

tensor([[[2., 3., 4.]],

        [[5., 1., 2.]]])

In [207]:
print(t7[0])
print(t7[0][0])
print(t7[0][0][0])
print(t7[1])
print(t7[1][0])
print(t7[1][0][0])

tensor([[2., 3., 4.]])
tensor([2., 3., 4.])
tensor(2.)
tensor([[5., 1., 2.]])
tensor([5., 1., 2.])
tensor(5.)


In [217]:
print(t7[0,0,1])
print(t7[1])
print(t7[1,:,0])

tensor(3.)
tensor([[5., 1., 2.]])
tensor([5.])


# Tensor and Numpy

In [227]:
import numpy as np

In [228]:
arr = np.arange(1.0, 10.0)
print(arr)

[1. 2. 3. 4. 5. 6. 7. 8. 9.]


### Change to tensor


In [229]:
tr = torch.from_numpy(arr)
print(tr)

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64)


When converting numpy array to pytorch tensor, it retains numpy datatype

In [233]:
arr = np.arange(1,10)
print(arr)
print(arr.dtype)
tr = torch.from_numpy(arr)
print(tr)
print(tr.dtype)

[1 2 3 4 5 6 7 8 9]
int64
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.int64


### Chage to numpy

In [237]:
tr1 = torch.tensor([1,2,3,4,5])
print(tr1)
arr1 = tr1.numpy()
print(arr1)
print(arr1.dtype)
print(type(arr1))

tensor([1, 2, 3, 4, 5])
[1 2 3 4 5]
int64
<class 'numpy.ndarray'>


In [262]:
#If we are using CPU, both objects will share the same memory location.
x = torch.ones(4)
print(x, type(x))
y = x.numpy()
print(y, type(y))
x.add_(1)
print(x)
print(y)

tensor([1., 1., 1., 1.]) <class 'torch.Tensor'>
[1. 1. 1. 1.] <class 'numpy.ndarray'>
tensor([2., 2., 2., 2.])
[2. 2. 2. 2.]


# Random number generation

In [255]:
tr_rand = torch.rand(2,3)
print(tr_rand)

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])


In [256]:
#Random but reproducible tensors using seed
seed = 42
torch.manual_seed(seed)
tr_rand = torch.rand(2,3)
print(tr_rand)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])


# GPU access with Pytorch

In [266]:
#MPS for Mac M1
if torch.backends.mps.is_available():
    print("MPS is available")
else:
    print("MPS is not available, using CPU")

MPS is available


In [269]:
#Setup device agnostic code i.e. use GPU if it is available otherwise use CPU
device = torch.device('mps') if torch.backends.mps.is_available() else 'cpu'
print(device)

mps


In [272]:
#Count number of devices in gpu
print(torch.cuda.device_count())  # This works for CUDA, not MPS
#For MPS, there is only one GPU available

0


In [275]:
#Putting tensors and models on the GPU
t9 = torch.tensor([1,2,3])
print(t9, t9.device)
t9 = tensor.to(device)
print(t9, t9.device)

tensor([1, 2, 3]) cpu
tensor([1., 2., 3.], device='mps:0') mps:0
